### ISSUE TITLE
ROS1 Melodic on Windows 10 Icons not displaying

### ISSUE THREAD

**Issue by arek20** [ros-visualization/rqt_plot#42] opened 2019-11-13 22:23 UTC
When going through the ROS tutorial for Beginners after Melodic install on Windows 10, the ros_graph and ros_plot within the window icons are not displaying at all (I went all the way through the whole tutorial, step-by-step, up to Section 6)

![image](https://user-images.githubusercontent.com/23062462/68809568-31b47000-063a-11ea-98cb-8f1601a7c049.png)

**Comment by dirk-thomas** [comment] 2020-09-23 20:10
I will close this as a duplicate of a more generic ticket in `qt_gui_core` where the change would need to happen: ros-visualization/qt_gui_core#238.

**Closed by dirk-thomas** 2020-09-23 20:10 UTC
Labels: duplicate
