### ISSUE TITLE
No plot on ROS Noetic

### ISSUE THREAD

**Issue by G-Pereira** [ros-visualization/rqt_plot#63] opened 2020-06-09 13:09 UTC
No data is shown when ploting any kind of topic on ROS Noetic and Ubuntu 20.04. Windows stay empty and adding a topic in the topic bar doesn't light up the plus button.
Launching rqt_plot from the terminal specifying the topic path also yields a blank graph and no topic selected.

**Comment by dirk-thomas** [comment] 2020-08-05 23:56
Without any further context I have to assume that this is a duplicate of #57 and will go ahead and close it.

If that is not the case please comment with steps to reproduce and (if applicable) any error messages and the ticket can be reopened.

**Closed by dirk-thomas** 2020-08-05 23:56 UTC
