### ISSUE TITLE
Matplotlib

### ISSUE THREAD

**Issue by ll7** [ros-visualization/rqt_plot#50] opened 2020-03-16 20:57 UTC
Hello,
first time using rqt_plot on a new Ubuntu machine, I had the following error message.
```bash
rqt_plot
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_qt5agg.py", line 77, in paintEvent
    self.resizeEvent(event)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_plot/data_plot/mat_data_plot.py", line 110, in resizeEvent
    self.figure.tight_layout()
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 2031, in tight_layout
    self.subplots_adjust(**kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1881, in subplots_adjust
    self.subplotpars.update(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 241, in update
    raise ValueError('bottom cannot be >= top')
ValueError: bottom cannot be >= top
Aborted (core dumped)
```
I "solved" the error by using `pip install matplotlib`. I don't know if it's a common problem, but I wanted to let you know.

Ubuntu 18.04
Ros Melodic

Terminal output from pip install:

```bash
pip install matplotlib
Collecting matplotlib
  Downloading https://files.pythonhosted.org/packages/9d/40/5ba7d4a3f80d39d409f21899972596bf62c8606f1406a825029649eaa439/matplotlib-2.2.5-cp27-cp27mu-manylinux1_x86_64.whl (12.8MB)
    100% |████████████████████████████████| 12.8MB 104kB/s 
Collecting cycler>=0.10 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting numpy>=1.7.1 (from matplotlib)
  Using cached https://files.pythonhosted.org/packages/3a/5f/47e578b3ae79e2624e205445ab77a1848acdaa2929a00eeef6b16eaaeb20/numpy-1.16.6-cp27-cp27mu-manylinux1_x86_64.whl
Collecting backports.functools-lru-cache (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/da/d1/080d2bb13773803648281a49e3918f65b31b7beebf009887a529357fd44a/backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl
Collecting subprocess32 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/32/c8/564be4d12629b912ea431f1a50eb8b3b9d00f1a0b1ceff17f266be190007/subprocess32-3.5.4.tar.gz (97kB)
    100% |████████████████████████████████| 102kB 1.8MB/s 
Collecting kiwisolver>=1.0.1 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/3d/78/cb9248b2289ec31e301137cedbe4ca503a74ca87f88cdbfd2f8be52323bf/kiwisolver-1.1.0-cp27-cp27mu-manylinux1_x86_64.whl (93kB)
    100% |████████████████████████████████| 102kB 1.9MB/s 
Collecting pytz (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl (509kB)
    100% |████████████████████████████████| 512kB 1.2MB/s 
Collecting six>=1.10 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
    100% |████████████████████████████████| 235kB 1.4MB/s 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/5d/bc/1e58593167fade7b544bfe9502a26dc860940a79ab306e651e7f13be68c2/pyparsing-2.4.6-py2.py3-none-any.whl (67kB)
    100% |████████████████████████████████| 71kB 1.8MB/s 
Collecting setuptools (from kiwisolver>=1.0.1->matplotlib)
  Downloading https://files.pythonhosted.org/packages/f9/d3/955738b20d3832dfa3cd3d9b07e29a8162edb480bf988332f5e6e48ca444/setuptools-44.0.0-py2.py3-none-any.whl (583kB)
    100% |████████████████████████████████| 583kB 1.2MB/s 
Building wheels for collected packages: subprocess32
  Running setup.py bdist_wheel for subprocess32 ... done
  Stored in directory: /home/luttkule/.cache/pip/wheels/68/39/1a/5e402bdfdf004af1786c8b853fd92f8c4a04f22aad179654d1
Successfully built subprocess32
Installing collected packages: six, cycler, numpy, backports.functools-lru-cache, subprocess32, setuptools, kiwisolver, pytz, python-dateutil, pyparsing, matplotlib
Successfully installed backports.functools-lru-cache-1.6.1 cycler-0.10.0 kiwisolver-1.1.0 matplotlib-2.2.5 numpy-1.16.6 pyparsing-2.4.6 python-dateutil-2.8.1 pytz-2019.3 setuptools-44.0.0 six-1.14.0 subprocess32-3.5.4
```
I am not sure, whether I hadn't installed matplotlib at all in python 2.7.

I guess it might be helpful to mention matplotlib as a python dependencie of rqt_plot?

**Comment by gokhansolak** [comment] 2020-03-20 13:01
I have the same problem, except `pip install matplotlib` does not solve it, as matplotlib is already installed. 

I just upgraded Ubuntu 16.04 to 18.04 and did a fresh install of ROS Melodic. When I run `rqt_plot` it does not render the plot and shows a squeezed window as follows:

![image](https://user-images.githubusercontent.com/6887994/77165369-0dfeac00-6aaa-11ea-9ea7-b5ae69d1895f.png)

If I resize it vertically, it will give the same error and crash.
![image](https://user-images.githubusercontent.com/6887994/77165544-6df55280-6aaa-11ea-8581-649f21867b3a.png)

matplotlib is installed by the package manager for both python 2 and 3 in its latest version.

`rqt_plot --clear-config` does not solve it either.

I can add rqt_plot to a `rqt_gui` window without a problem though.

**Comment by ll7** [comment] 2020-03-20 13:05
I don't recall trying any other "fixes" than described above.

**Comment by dirk-thomas** [comment] 2020-03-26 05:46
This seems like a duplicate of #35.

**Comment by gokhansolak** [comment] 2020-03-26 10:25
In #35, the error occurs when the plot widget is moved in rqt_gui. For me, rqt_plot does not work alone, but it works when put into rqt_gui. I think this may be connected with the default configuration of rqt_plot being messed up because the initial top and bottom parameters are zero (at guess). I searched docs but could not find any config file.

**Closed** 2020-04-03 17:51 UTC
Labels: duplicate
