### ISSUE TITLE
[ROS2]rqt_plot can't plot data with the QoS profile of qos_profile_sensor_data

### ISSUE THREAD

**Issue by rosesue** [ros-visualization/rqt_plot#40] opened 2019-10-17 02:51 UTC
I created a publisher with rclpy.qos.qos_profile_sensor_data
```
self.pub = self.create_publisher(Int16, OUTPUT_TOPIC, qos_profile_sensor_data)
```
However, rqt_plot can't plot the data from this publisher, though there is data existing in OUTPUT_TOPIC. 
When I changed the profile as something like the following, it works.
```
self.pub = self.create_publisher(Int16, OUTPUT_TOPIC, 10)
```
it seems that rqt_plot don't support a specific QoS profile?

**Comment by dirk-thomas** [comment] 2019-10-18 15:43
This is certainly a problem and generically applies to all rqt plugins. I will go ahead and close this as a duplicate of ros-visualization/rqt#187.

**Closed by dirk-thomas** 2019-10-18 15:43 UTC
Labels: duplicate
