### ISSUE TITLE
plot export TypeError

### ISSUE THREAD

**Issue by svisschers** [ros-visualization/rqt_plot#11] opened 2018-03-12 13:34 UTC
I use rqt_plot in ROS Kinetic to plot an angular velocity:
`rqt_plot /rovio/odometry/twist/twist/angular/y`

Then I get a nice plot, which I want to export. So I get the dropdown menu using the right mouse button and select export. Then I select in the pop-up menu: 
- Item to export: Entire Scene > Plot > Viewbox
- Export format: Image File (PNG, TIF, JPG, ...)
- Export options: params (default values):
    * width: 678
    * height: 312
    * antialias: true
    * background: white (= #ffffff)

When I then press "export", I get a browser to specify the location of the image to be created, and when I enter a name and save the image in a .png format, I get the following error message in the terminal and the image is not created:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyqtgraph/exporters/Exporter.py", line 77, in fileSaveFinished
    self.export(fileName=fileName, **self.fileDialog.opts)
  File "/usr/lib/python2.7/dist-packages/pyqtgraph/exporters/ImageExporter.py", line 70, in export
    bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
TypeError: 'float' object cannot be interpreted as an index` 

Any idea what goes wrong here?

**Comment by dirk-thomas** [comment] 2018-03-21 23:09
It looks to me that the `width` or `height` parameter is a float but should be an integer.

You might want to file this issues at the package which raises the exception: https://github.com/pyqtgraph/pyqtgraph/ If you do so please link to the new ticket so that future readers can find the upstream ticket.

**Comment by dirk-thomas** [comment] 2018-03-29 20:07
Closing as a duplicate of pyqtgraph/pyqtgraph#651.

**Closed by dirk-thomas** 2018-03-29 20:07 UTC
Labels: bug, duplicate
